Created class Label with properties visibile on diagram and method add_item
brytebee/myCatalog pull request #30
Opened 2022-04-18 13:01 UTC by VuDej

Hi,
- added class Label
- visible properties on the diagram implemented in the constructor
- added public method add_item
- added label as a property of the item object

2022-04-18 13:14 UTC, brytebee requested changes
Hi, @VuDej 👋, 

Great work on making the changes 👏 👏 
You've done well implementing some of the requested changes requested by the previous review, but there are still some which aren't addressed yet.


# Suggested changes
_Check the comments under the review._

![](https://media.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif)


Cheers and Happy coding!👏👏👏

2022-04-18 13:14 UTC, brytebee commented on src/classes/label.rb
> +  attr_writer :id
- [ ] **Required:** Kindly change the id to be read-only, currently it can be edited after the label had been created.

2022-04-19 05:17 UTC, Beardless-sheik approved these changes
Hi @VuDej . Great work on this class. It works perfectly as expected from the project brief. We can go ahead and merge it.

2022-04-19 07:57 UTC, brytebee approved these changes
Hi @VuDej 👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

Good luck! 🎉

2022-04-19 07:57 UTC, merged